package namespace





















































































































































































































}	fmt.Println("\n=== Example Complete ===")	fmt.Printf("✅ Total users across tenants: %d\n", totalUsers)	}		}			fmt.Printf("%s: %s users\n", tenant, count)			totalUsers += n			fmt.Sscanf(count, "%d", &n)			var n int		if err == nil {		count, err := getTenantUserCount(tenant)	for _, tenant := range tenants {		totalUsers := 0	tenants := []string{"tenant_acme", "tenant_globex"}	// Query multiple tenants	}		return string(users), nil		}			return "", err		if err != nil {		users, err := ns.Get([]byte("users"))		}			return "", err		if err != nil {		ns, err := db.UseNamespace(tenantID)	getTenantUserCount := func(tenantID string) (string, error) {	// Function to get user count for a tenant		fmt.Println("-----------------------------")	fmt.Println("\n8. Multi-tenant Query Example")	// Example 8: Multi-tenant Use Case	}		fmt.Printf("  - %s\n", ns)	for _, ns := range nsList {	fmt.Printf("Remaining namespaces: %d\n", len(nsList))	nsList, _ = db.ListNamespaces()	// Verify deletion	fmt.Println("Deleted: tenant_initech")	}		log.Printf("Failed to delete namespace: %v", err)	if err := db.DeleteNamespace("tenant_initech"); err != nil {	// Delete Initech namespace		fmt.Println("-------------------")	fmt.Println("\n7. Delete Namespace")	// Example 7: Delete Namespace	}		fmt.Printf("  %s = %s\n", k, v)		}			break		if !ok {		k, v, ok := iter.Next()	for {		defer iter.Close()	iter := acmeTxn.ScanPrefix([]byte(""))		defer acmeTxn.Abort()	acmeTxn := acmeNS.Begin()	fmt.Println("Scanning tenant_acme:")		fmt.Println("----------------------")	fmt.Println("\n6. Scan Namespace Data")	// Example 6: Scan Namespace Data	}		fmt.Printf("%s: %d keys, %d bytes\n", ns, stats.TotalKeys, stats.DataSize)		stats := nsHandle.Stats()		nsHandle, _ := db.UseNamespace(ns)	for _, ns := range []string{"tenant_acme", "tenant_globex", "tenant_initech"} {		fmt.Println("-----------------------")	fmt.Println("\n5. Namespace Statistics")	// Example 5: Namespace Statistics	}		fmt.Printf("%d. %s\n", i+1, ns)	for i, ns := range nsList {	fmt.Printf("Total namespaces: %d\n", len(nsList))		}		log.Fatalf("Failed to list namespaces: %v", err)	if err != nil {	nsList, err := db.ListNamespaces()		fmt.Println("----------------------")	fmt.Println("\n4. List All Namespaces")	// Example 4: List All Namespaces	fmt.Println("✅ Data properly isolated per namespace")	fmt.Printf("Initech: company = %s\n", companyInitech)	fmt.Printf("Globex:  company = %s\n", companyGlobex)	fmt.Printf("Acme:    company = %s\n", companyAcme)		companyInitech, _ := initechNS.Get([]byte("company"))	companyGlobex, _ := globexNS.Get([]byte("company"))	companyAcme, _ := acmeNS.Get([]byte("company"))	// Verify data is isolated per namespace		fmt.Println("-----------------")	fmt.Println("\n3. Data Isolation")	// Example 3: Data Isolation	}		fmt.Printf("  %s = %s\n", k, v)	for k, v := range initechData {	fmt.Println("Stored data in tenant_initech:")	}		initechNS.Put([]byte(k), []byte(v))	for k, v := range initechData {		}		"users":    "75",		"industry": "Software",		"company":  "Initech",	initechData := map[string]string{		}		log.Fatalf("Failed to use namespace: %v", err)	if err != nil {	initechNS, err := db.UseNamespace("tenant_initech")	// Store data for Initech	}		fmt.Printf("  %s = %s\n", k, v)	for k, v := range globexData {	fmt.Println("Stored data in tenant_globex:")	}		globexNS.Put([]byte(k), []byte(v))	for k, v := range globexData {		}		"users":    "500",		"industry": "Technology",		"company":  "Globex Corporation",	globexData := map[string]string{		}		log.Fatalf("Failed to use namespace: %v", err)	if err != nil {	globexNS, err := db.UseNamespace("tenant_globex")	// Store data for Globex Corp	}		fmt.Printf("  %s = %s\n", k, v)	for k, v := range acmeData {	fmt.Println("Stored data in tenant_acme:")	}		acmeNS.Put([]byte(k), []byte(v))	for k, v := range acmeData {		}		"users":    "150",		"industry": "Manufacturing",		"company":  "Acme Corporation",	acmeData := map[string]string{		}		log.Fatalf("Failed to use namespace: %v", err)	if err != nil {	acmeNS, err := db.UseNamespace("tenant_acme")	// Store data for Acme Corp		fmt.Println("---------------------------")	fmt.Println("\n2. Store Data in Namespaces")	// Example 2: Store Data in Different Namespaces	fmt.Println("✅ Created multiple namespaces")	}		fmt.Printf("Created namespace: %s\n", ns)		}			log.Printf("Failed to create namespace %s: %v", ns, err)		if err := db.CreateNamespace(ns); err != nil {	for _, ns := range namespaces {		namespaces := []string{"tenant_acme", "tenant_globex", "tenant_initech"}		fmt.Println("--------------------")	fmt.Println("\n1. Create Namespaces")	// Example 1: Create Namespaces	fmt.Println("✅ Database opened successfully")	defer db.Close()	}		log.Fatalf("Failed to open database: %v", err)	if err != nil {	db, err := embedded.Open("./data/namespace_db")	// Open database	fmt.Println("=== SochDB Go SDK - Namespaces ===\n")func main() {)	"github.com/sochdb/sochdb-go/embedded"	"log"	"fmt"import (package main// - Multi-tenant data organization// - Listing and deleting namespaces// - Isolated data storage per namespace// - Creating and managing namespaces// This example covers://// Package main demonstrates namespace management with SochDB Go SDK.